### ISSUE TITLE
App not launching

### ISSUE THREAD

**Issue by federicochiesa** [doshidak/Max#11]
After the signing problems got solved the app worked fine, but now it started crashing on launch again... 
If I can be of any help sending any logs just ask.

**Comment by doshidak** [comment]
Hey @federicochiesa!

Sorry about the delayed response. I don't get any notifications when someone opens an issue for some reason, so I only saw this when I checked the repo just now.

Based on your description, you may have downloaded the version from PR #9 (the download was named `Max-0.9.2-24.zip`), which I accidentally signed with my personal development certificate, so that's probably why it's crashing again (since the provisioning profile expired).

I re-signed the app with a self-signed certificate in PR #10, so try [downloading the `Max-0.9.2-24-20191202.zip` file](https://github.com/doshidak/Max/releases/download/release-0.9.2/Max-0.9.2-24-20191202.zip). I'll close this for now, but if you're still having problems, feel free to re-open this issue with the crash log.

Thanks! :)
