### ISSUE TITLE
Crashed due to missing code signature

### ISSUE THREAD

**Issue by u-foka** [doshidak/Max#5]
Hy,

First let me thank you for your efforts to keep this great app alive!

I'm currently still running on Mojave in preparation to the Catalina switch I'm trying to get rid of all 32bit apps that I use, that's how I found your build :)

I have gatekeeper enabled, and after I allow the app to run it crashes immediately.
In the crash log the following seem to be the root cause:

> Dyld Error Message:
>   Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
>   Referenced from: /Applications/Max.app/Contents/Frameworks/musicbrainz3.framework/Versions/A/musicbrainz3
>   Reason: no suitable image found.  Did find:
> 	/usr/local/opt/openssl/lib/libssl.1.0.0.dylib: code signature in (/usr/local/opt/openssl/lib/libssl.1.0.0.dylib) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
> 	/usr/local/opt/openssl/lib/libssl.1.0.0.dylib: stat() failed with errno=1

Also atached the full report:
[Max_2019-10-25-202802_u-foka-macbook.crash.txt](https://github.com/doshidak/Max/files/3773334/Max_2019-10-25-202802_u-foka-macbook.crash.txt)

After signing the app with my test certificate I was able to start it.
`codesign --deep -f -s Test\ Signature /Applications/Max.app`

**Comment by doshidak** [comment]
Hey @u-foka, thanks for bringing this to my attention!

I might've misconfigured the MusicBrainz framework when I was recompiling it for 64-bit (kinda started mindlessly reconfiguring each framework project in Xcode cause there were so many haha), but I'll take a closer look!

From first glance (thanks for the super detailed logs by the way!), it appears that MusicBrainz uses `libssl`, which, if I remember correctly, wasn't included with the standard macOS libraries. I believe I had to use Homebrew (via `brew install openssl` or something along those lines) to obtain it.

As you've discovered, the entire app (including all frameworks) is not codesigned because I don't have any Apple accounts enrolled in the developer program for personal use. I'm thinking about signing up eventually, but for now, I just wanted to get a release version going so I could install it on all my Macs (speaking of which, never ran into any issues on my other Macs, which is strange).

Glad you were able to figure out a workaround though! I'll link this issue in the release notes in case other people run into the same problem :)

**Comment by u-foka** [comment]
I have no "valid" certificate either, I've created my own self signed test certificate to be able to run gdb for example.

I use XCA for such tasks, and enabled the following extensions for the cert:
```
X509v3 Key Usage:
Digital Signature
X509v3 Extended Key Usage:
Code Signing
Netscape Cert Type:
Object Signing
```

When you sign an app with such certificate macOS will still complain about "unidentified developer" but seems to work better in some cases than an app without any signiture.

**Comment by doshidak** [comment]
Oh interesting, that's good to know! I'll just sign the app that way and reupload it to the release then. Been awhile since I used Xcode, so I'm a little rusty haha. But thanks for the info :)

**Comment by ideoservo** [comment]
Max 0.9.2 crash at startup on Catalina fixed after doing the following commands in a term:
1)Install home brew (see https://brew.sh)
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
2) install openssl
brew install openssl
